### ISSUE TITLE
Unsuccessful in converting a certain tune from Aleste 2 MSX to VGM

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [digital-sound-antiques/kss2vgm#7]
Thanks for another ( ;) ) great tool :)
 
I'm having issues extracting and converting a specific tune from the kss mentioned in the title.
It includes an m3u playlist but I seem to be unable to make sense of which song # I have to specify for kss2vgm for a specific tune displayed in the playlist.
 
Could you advise for, as an example, "Aleste2 (PSG) (C)COMPILE 1989 [ SOUND 09 (title)"?
 
Thank you.
 
[Aleste 2 (MSX)(1989)(Compile)-kss.zip](https://github.com/digital-sound-antiques/kss2vgm/files/4487017/Aleste.2.MSX.1989.Compile.-kss.zip)

**Comment by okaxaki** [comment]
If you have trouble with file name with space character, rename the kss file first to avoid using spaces.

As for the song number, `$nn` part in .m3u file represents the song number in hex. kss2vgm only accepts decimal song number, thus for example, if the song number is $8F, `kss2vgm -s143 yourfile.kss` will work.

If you are not familier with hexadecimal number, try https://www.hexadecimaldictionary.com/

**Comment by TheStruggleForAntiSpaghetti** [comment]
Thanks :)
I was able to extract and convert the Aleste 2 title tune!
 
Might I suggest to mention this in the Readme? Or, because m3u playlists seem to use Hex, make possible to specify the song number in hex for KSS2VGM?

-s$8f for example.

After conversion, there's an issue during playback though - a constant buzz throughout the whole length of the tune.

[Aleste 2 (MSX)(1989)(Compile)-vgm.zip](https://github.com/digital-sound-antiques/kss2vgm/files/4501367/Aleste.2.MSX.1989.Compile.-vgm.zip)

**Comment by okaxaki** [comment]
Sorry for kss2vgm does not have enough argument parsing feature. I have a plan to rewite kss2vgm for rich command line options to node.js based but i have not started yet.

However, if you can use bash shell and `bc` command, hex to dec can be achived by:

```sh
bash$ s=`echo "ibase=16; 8F" | bc` ; kss2vgm -s$s filename.kss
```

As for constant buzz, some KSS contains incorrect SCC register access. SCC part can be removed by using vgm-strip:

```sh
bash$ vgm-strip -c k051649 filename.vgm
```

**Comment by TheStruggleForAntiSpaghetti** [comment]
I've installed VGM-Strip v0.1.2 from its repo (using NPM) under Windows.
I'm trying to apply it by using (since the source tune is from MSX, I'm using ay8910 instead of your proposed k051649):
`vgm-strip -c ay8910 -i "Aleste2(MSX)(1989)(Compile).vgm"` 
 
but get the following error:
`Please specify input file. Standard input can not be used on Windows.`

**Comment by okaxaki** [comment]
I have fixed windows problem. Please upgrade and try vgm-strip v0.1.3.

K051649 is the chip name of Konami SCC. I think `-c k051649` should be specified because KSS  possibly accesses the memory range mapped to the SCC cart even the song only uses YM2413 and PSG.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Thanks, I'll try and let you know.

**Comment by TheStruggleForAntiSpaghetti** [comment]
I've updated to v0.1.3 but I'm still getting the same error:
`Please specify input file. Standard input can not be used on Windows.`

**Comment by okaxaki** [comment]
On windows, both `-i` and `-o` options are required. The following command works.
```
vgm-strip -c <chipname> -i <inputfile> -o <outputfile>
```

If you still have the same problem, please make sure the version is 0.1.3 first by running `vgm-strip --version`. Then confirm that the error message you met is really for *input* file. If -o option is not specified, the resulting error message is very similar to input file but for output file like:
```
Please specify output file. Standard output can not be used on Windows.
               ^^^^^^
```

**Comment by TheStruggleForAntiSpaghetti** [comment]
Yes, that did it! :)
I was thrown off by ` Standard output will be used if not speicified.` in the help, which I interpreted as that the original file would be overwritten if not given.
 
The audio sounds really clean now.
 
One issue left though - the tune is being abruptly cut-off too soon.

**Comment by okaxaki** [comment]
i understood that the help is confusing for windows users. i will improve it.

As for song length, use -p option of kss2vgm to specify the desired song length in seconds.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Yay! That did it - thanks :)
 
If, after having used KSS2VGM garbled sound is heard, does one always have to use k051649 or can others also occur? If so, how can one know which one to use?

**Comment by okaxaki** [comment]
It's depends on kss file ... but in the most case K051649 is the reason.
I think using vgm player with muting feature is helpful to investigate errornous channels.
